### ISSUE TITLE
Scrap PR-based RFPs

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-docs#10]
RFP repo link: https://github.com/sora-xor/rfps

**Comment by WRRicht3r** [comment]
Done

**Comment by bgodlin** [comment]
@WRRicht3r Would it be advisable to remove `closed_rfps` and `open-rfps` folders from the original repo (https://github.com/sora-xor/rfps) and convert the stored rfps to issues? We could add references to the corresponding pull requests in each of the issues with the statuses set as `open` or `closed`.

**Comment by WRRicht3r** [comment]
Sure, feel free to make the changes, but I'm not the deciding factor in that repo, we would have to ask Makoto-san

**Comment by bgodlin** [comment]
Duplicates https://github.com/sora-xor/rfps/pull/56
