### ISSUE TITLE
Revise `Build` section

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-docs#154]
> - It seems that some sections in the *Consensus* should be moved to the guides on *Nominating validators (How to select validators effectively, filtering out validators)*
- Move *How to become a validator* in *Participating in the SORA Economy*

**Comment by bgodlin** [comment]
@Tieumsan @WRRicht3r upon revisiting the https://github.com/sora-xor/sora-docs/blob/develop/src/consensus.md page, I've come to the realization that the content within this entire page is not related to development aspects. Therefore, I am thinking of relocating the entire page from its current placement within the `Build` section to a more suitable position, possibly close to the economy-related pages, within the `Introduction` section.

**Comment by WRRicht3r** [comment]
Hello @bgodlin, that makes sense to me. Thanks
