### ISSUE TITLE
Comprehensive Guide on Opening an HRMP Channel with SORA

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-docs#198]
# Description

In order to foster seamless collaboration and interoperability within the Dotsama ecosystem, it is crucial to provide ecosystem developers with clear and detailed guidelines on how to open an HRMP channel with us. This comprehensive guide aims to empower developers by equipping them with the knowledge and resources necessary to establish efficient HRMP channels, enabling the exchange of information and value across different Substrate-based projects.

# Relevant materials

- https://docs.moonbeam.network/builders/interoperability/xcm/xc-integration/
- https://docs.astar.network/docs/xcm/integration/hrmp
- https://guide.kusama.network/docs/build-hrmp-channels/

# Relevant issues
- https://github.com/sora-xor/sora2-network/issues/594
- https://github.com/sora-xor/sora2-network/issues/593
- https://github.com/sora-xor/sora2-network/issues/592
- https://github.com/sora-xor/sora2-network/issues/591

# DoD

Feel free to drop the guide as a comment. This way, we'll have the markdown file ready for easy integration into the documentation platform after the review. It'll make the process quicker and more convenient for everyone involved.

**Comment by Tieumsan** [comment]
SORA Assets: https://github.com/sora-xor/sora2-parachain/issues/17

**Comment by WRRicht3r** [comment]
This is also a [good sauce](https://guide.kusama.network/docs/build-hrmp-channels/) for the base of the article, as it is brand agnostic, although specific for Kusama

**Comment by bgodlin** [comment]
Completed as part of https://github.com/sora-xor/sora-docs/pull/136
