### ISSUE TITLE
Linking SORA Wiki

### ISSUE THREAD

**Issue by WRRicht3r** [sora-xor/sora-docs#24]
- [x] https://github.com/sora-xor/sora-docs/issues/83
- [x] #84

**Comment by outoftardis** [comment]
- [ ] set up a redirect from the old wiki to the new one

**Comment by bgodlin** [comment]
May be merged combined with https://github.com/sora-xor/sora-docs/issues/83

**Comment by WRRicht3r** [comment]
Looks like @Tieumsan is the one who can make this merge

**Comment by Tieumsan** [comment]
@WRRicht3r which merge ? This issue is not linked to any PR, and there is no open PR.
Please let me know what you need if I can help

**Comment by bgodlin** [comment]
@WRRicht3r Do I understand correctly that we want to host the documentation under [wiki.sora.org](https://wiki.sora.org), in the same location as the current Gitbook project? Or should we use GitHub Pages as the deployment platform, where we currently host all the previews ([https://sora-xor.github.io/sora-docs/](https://sora-xor.github.io/sora-docs/))?

**Comment by f33r0** [comment]
@WRRicht3r vitepress does not have a normal redirect mechanism.
If the user cannot find the page, he will be taken to a page with an offer to go to the main page, and from there it is not difficult to find what he needs. Also, I think this is a very special case.

**Comment by bgodlin** [comment]
> @WRRicht3r vitepress does not have a normal redirect mechanism. If the user cannot find the page, he will be taken to a page with an offer to go to the main page, and from there it is not difficult to find what he needs. Also, I think this is a very special case.

https://github.com/sora-xor/sora-docs/issues/83 is the better scope for this comment

**Comment by bgodlin** [comment]
There is no necessity for maintaining this distinct abstract issue.
