### ISSUE TITLE
Add Kenonomics

### ISSUE THREAD

**Issue by WRRicht3r** [sora-xor/sora-docs#252]
Based on the information outlined in the community-produced [Kensetsu tokenomics](https://medium.com/@shibarimoto/kensetsu-ken-356077ebee78), Kenonomics information should be added to the SORA Wiki

**Comment by Tieumsan** [comment]
@WRRicht3r I think this task is done. A good practice is to link the pull request to the task so that when the PR is closed, the task is completed automatically. 

Please update the status of the task accordingly.

**Comment by WRRicht3r** [comment]
Will do ser, thank you
