### ISSUE TITLE
Add the links to community blogs

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-docs#37]

**Comment by outoftardis** [comment]
Please provide the list of links to add

**Comment by outoftardis** [comment]
The page where the links should be added: https://github.com/sora-xor/sora-docs/blob/develop/src/blogs.md

**Comment by WRRicht3r** [comment]
Hello, the links so far are:
- SORA Daily [Twitter](https://twitter.com/SoraDaily_), [Telegram](https://t.me/SORAdaily)
- SORA Daily ES [Telegram](https://t.me/soradailyspanish), [Twitter](https://twitter.com/Soradailyspa)
- SORA Daily JP [Telegram](https://t.me/SORADaily_Japanese)
- SORA Daily CZ [Telegram](https://t.me/SORADailyCzech)
- SORA Daily NL [Telegram](https://t.me/SORAdaily_dutch)
- SORA news [Website](https://soranews.io), [Twitter](https://twitter.com/soranews_io), [Medium](https://medium.com/@soranews)
- SORA Academy [Medium](https://medium.com/sora-academy)
