### ISSUE TITLE
Add a guide "How to Request Identity Judgment For SORA"

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-docs#38]
https://docs.google.com/document/d/1AugYAY4IZTNN7agfmx8mhJhnyzwXG-IMW3XA4uupxNU/edit?usp=sharing

**Comment by WRRicht3r** [comment]
Hi @bgodlin has the page for this been added?

**Comment by outoftardis** [comment]
This should probably expand this guide we already have: https://github.com/sora-xor/sora-docs/blob/develop/src/id.md
