### ISSUE TITLE
Fix images in create-an-address.md

### ISSUE THREAD

**Issue by outoftardis** [sora-xor/sora-docs#41]
The second part of the `create-an-address.md` file contains links to images that are either missing or incorrect. In #40 I've put comments around such instances for now, but it should be fixed properly.

**Comment by bgodlin** [comment]
Also this issue is preventing the project from successfully building https://github.com/sora-xor/sora-docs/actions/runs/5049822213/jobs/9059763165

**Comment by outoftardis** [comment]
I think this was closed by accident.
