### ISSUE TITLE
Add site metadata

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-docs#55]
https://vitepress.dev/reference/site-config#site-metadata

**Comment by bgodlin** [comment]
@WRRicht3r Should we assign someone from the marketing (SEO) team to handle this task?

**Comment by outoftardis** [comment]
For individual pages: https://vitepress.dev/reference/frontmatter-config#head

**Comment by WRRicht3r** [comment]
Can we have the file implemented to our repos so I can share it with the BX team for them to add the required info? 
I think they could also give us the info and we can add it to the metadata file

**Comment by outoftardis** [comment]
> Can we have the file implemented to our repos so I can share it with the BX team

what do you mean by that?
