### ISSUE TITLE
Move relevant pages from the current wiki

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-docs#6]
# Problem
The new documentation is missing content from certain pages and only includes references to them. This can be seen in the following example (running a node):

- Deployed page URL: https://wiki.sora.org/guides/staking/how-to-run-a-sora-mainnet-node
- Markdown file for the current wiki page: https://github.com/sora-xor/wiki/blob/master/guides/staking/how-to-run-a-sora-mainnet-node.md
- Location of the same file in the new wiki repository: https://github.com/sora-xor/sora-docs/blob/develop/src/running-a-node.md

Copying and pasting the markdown file results in an error, as shown in the following figure:

![Screenshot 2023-04-21 at 12 27 22](https://user-images.githubusercontent.com/37313677/233616617-067d94f8-cf21-4ded-ab76-bbc8db61d0dd.png)

# Resolution
To resolve this issue, manual editing of the markdown files is necessary to ensure compatibility with the new wiki platform, vitepress.dev.

**Comment by WRRicht3r** [comment]
I am currently adding pages to the wiki

**Comment by bgodlin** [comment]
The following pages are not migrated yet:
- https://wiki.sora.org/guides/polkaswap/staking
- https://wiki.sora.org/guides/polkaswap/rewards and https://sora-xor.github.io/sora-docs/rewards are different 
- https://wiki.sora.org/guides/polkaswap/explore
- https://wiki.sora.org/guides/polkaswap/statistics
- https://wiki.sora.org/guides/polkaswap/other-features
- https://wiki.sora.org/guides/how-to-stake-your-xor

**Comment by WRRicht3r** [comment]
@bgodlin can you support adding a Polkaswap collapsable subsection with the to be migrated pages inside? I don't want to break it, not reveal my dishwasher's IP

**Comment by bgodlin** [comment]
> @bgodlin can you support adding a Polkaswap collapsable subsection with the to be migrated pages inside? I don't want to break it, not reveal my dishwasher's IP

Certainly, I will take on the task of reassigning this issue to myself. Additionally, we need to verify if there have been any recent contributions to Gitbook, as we should migrate those as well.

**Comment by WRRicht3r** [comment]
I have found we are missing 
- https://wiki.sora.org/architecture/interoperability/evm
- https://wiki.sora.org/architecture/interoperability
- https://wiki.sora.org/guides/how-to-claim-harvested-pwsap-or-the-val-airdrop or https://wiki.sora.org/guides/rewards
