### ISSUE TITLE
Address Grug's feedback for Old Wiki

### ISSUE THREAD

**Issue by WRRicht3r** [sora-xor/sora-docs#60]
Our dear contributor Grug left the following feedback

1) JpGames tokens are burned.
2)I can't find XST tokenomics.
3)TBCD tokenomics and info are missing.
4) staking page is misleading. it doesn't tell anything about staking.
5)Fearless wallet app page in wiki needs to mention that FW *have* not *will have* XOR staking. (With tutorial please). 
6)Please add an nice image of the wallet in this page. https://wiki.sora.org/ecosystem/sora-mobile-app

I have addressed the feedback in the old wiki, now it needs implementation on the new one

**Comment by bgodlin** [comment]
@WRRicht3r considering that all tasks in this repository are related to documentation, the current `documentation` seems unnecessary

**Comment by WRRicht3r** [comment]
Issues were addressed
