### ISSUE TITLE
Update changelog page

### ISSUE THREAD

**Issue by outoftardis** [sora-xor/sora-docs#75]
Q:
> There is a "Changelog" page (https://raw.githubusercontent.com/sora-xor/sora-docs/develop/src/changelog.md) in the wiki that doesn't seem to contain much info. It's currently a part of the "Getting started" section, but I don't think it's relevant there. Maybe the Ecosystem chapter would be a better place for it? Also, it contains empty links, should they be updated?

A:
> This should link to the SORA backend changelogs on git, I think we need some more work on these

**Comment by WRRicht3r** [comment]
I think we can add https://github.com/sora-xor/sora2-network/releases for the SORA blockchain changelog
