### ISSUE TITLE
Transition of links from old to new wiki

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-docs#83]
### Problem statement

As we build the new wiki for SORA, we need to update the links that redirect to the former wiki to set the redirection to the new wiki.

### Definition of Done

- [x] List of places where the old wiki (https://wiki.sora.org/master) is used

**Comment by bgodlin** [comment]
An up-to-date list will always be available at https://github.com/sora-xor/wiki/blob/master/SUMMARY.md
