### ISSUE TITLE
Apply the correct replacements or mirrors for all the present links

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-docs#84]
Make sure that we have the correct replacements or mirrors for all the links in https://docs.google.com/spreadsheets/d/15QXumaISgZ_elw_9gzXer6TyfrZhsjQVscuAglwYqIM/edit?usp=sharing so that there are no issues once the new one is deployed

**Comment by WRRicht3r** [comment]
Ah, a TON of links to review and correct! AMAZING.

**Comment by bgodlin** [comment]
> Ah, a TON of links to review and correct! AMAZING.

I think that we should divide it and address the lower priority tag

**Comment by bgodlin** [comment]
Completion was inherited by https://github.com/sora-xor/sora-docs/issues/83
