### ISSUE TITLE
[Documentation] Write article in wiki for Parachain Bridge Public Test

### ISSUE THREAD

**Issue by pg-vlad** [sora-xor/sora-docs#99]
Write article in wiki for Parachain Bridge Public Test

https://soramitsu.atlassian.net/wiki/spaces/SE/pages/2224816140/Environments

**Comment by bgodlin** [comment]
Part of #7

**Comment by bgodlin** [comment]
@ghostit93 In the future, I plan to include the missing content in this user-oriented documentation, along with the existing information. Please note that this documentation is intended for users and not developers or quality assurance teams.
